### PR TITLE
style: 主题色改为#2460E0

### PR DESCRIPTION
**Pull request by xxkiwi**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by lianghx-319** [comment]
你从哪儿切的分支呀

**Comment by xxkiwi** [comment]
> 你从哪儿切的分支呀

only-component

**Comment by lianghx-319** [comment]
> > 你从哪儿切的分支呀
> 
> 
> 
> only-component

应该从 dev 切出来..现在很多不是你的改动

**Comment by lianghx-319** [comment]
#60

**Pull request closed without merging**
